### ISSUE TITLE
What is the process for installing in WSL2?

### ISSUE THREAD

**Issue by cheslijones** [FiloSottile/mkcert#357]
I honestly can't say if the problem is with WSL2, Docker, Kubernetes, Minikube or mkcert, but I'm wondering: what is the installation process is for WSL2? Should it be done Windows side, or should it be done inside WSL2?

I have the same process for my Linux partition and macOS. The deployment works fine those two but not inside of WSL. The deployment is basically the following:

```
# Download and install mkcert
if [[ `uname` = "Darwin" ]] then
    brew install mkcert
    brew install nss
else
    curl -Lo mkcert https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-amd64 && \
        sudo install mkcert /usr/local/bin/
fi

# Installing tls certificate
mkcert -install

# Installing tls certificate
mkcert localhost 127.0.0.1 ::1

# Installing cert-manager locally
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.2.0/cert-manager.yaml

# Add the certificates to secrets
kubectl create secret tls tls-localhost-dev --key=localhost+2-key.pem --cert=localhost+2.pem -n dev

# Create the tls service that will attach to ingress-nginx
kubectl apply -f k8s/dev/tls.yaml
```
At the end of this (on macOS and Linux), you should be able to spin-up the application, navigate to `localhost` and there is a valid TLS certificate. 

Doesn't work on WSL2 however and while the error is Kubernetes related:
```
 Type     Reason         Age                  From          Message
  ----     ------         ----                 ----          -------
  Warning  ErrGetKeyPair  4m30s (x9 over 19m)  cert-manager  Error getting keypair for CA issuer: secret "tls-localhost-dev" not found
  Warning  ErrInitIssuer  4m30s (x9 over 19m)  cert-manager  Error initializing issuer: secret "tls-localhost-dev" not found
```
(`tls-localhost-dev` very clearly does exist, btw)...

I can't help but think it is an issue with WSL2 and the `mkcert` certificates. WSL2 does some weird stuff with networking to say the least. 

Should `mkcert` not be used and certificates not installed directly in WSL2? Should they go into Windows itself?

**Comment by rfay** [comment]
If you want the windows-side browser to trust something that's in wsl2 you have to do a little bit.  I think we have this pretty well dialed in in the instructions for ddev, https://ddev.readthedocs.io/en/latest/#installation-or-upgrade-windows-wsl2

What we do is create the CA on the Windows side and then tell WSL2 to use that one.

**Comment by cheslijones** [comment]
Thanks for the documentation. 

Unfortunately, I've been unable to get it `mkcert` working for my use case and still run into the same issues when it comes to deploying the local dev k8s cluster. Likely going to have to chalk this up to another issue unique to WSL2 (given it works fine in Linux and macOS) and move on. 

I'm pretty sure `mkcert` is doing what it needs to do, so I'll check with the `cert-manager` devs to see if they might have any ideas.

**Comment by cheslijones** [comment]
Ok, got this figured out with some help:

- https://github.com/Microsoft/WSL/issues/3161#issuecomment-451863149
- https://ddev.readthedocs.io/en/latest/#installation-or-upgrade-windows-wsl2
- https://www.haveiplayedbowie.today/blog/posts/secure-localhost-with-mkcert/

This is what worked for my use case. Granted, I didn't test it without installing `mkcert` into WSL, so that step may not be necessary:

1. Use `choco` to install `mkcert`: `choco install -y mkcert`
2. In Windows, `mkcert -install`
3. WSL install `mkcert` (again, not 100% sure this is necessary): 
   ```
   curl -Lo mkcert https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-amd64 &&
      sudo install mkcert /usr/local/bin/
   ```
4. In WSL, `mkcert -install` (again, not 100% sure this is necessary)
5. In Windows:
   ```
   mkcert localhost 127.0.0.1 ::1
   ```
6. This will generate them in your `C:\Users\<user>\` directory by default
7. Copy them into WSL, which for my use case is the root of my project
8. Then for my use case I run: 
   ```
   kubectl create secret tls tls-localhost-dev --key=localhost+2-key.pem --cert=localhost+2.pem -n dev 
   ```
9. For my use case, I then run `kubectl apply -f k8s/dev/tls.yaml` which contains:
   ```
    apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: letsencrypt-dev-issuer
      namespace: cert-manager
    spec:
      ca:
        secretName: tls-localhost-dev
    ---
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: letsencrypt-dev-certificate
      namespace: cert-manager
    spec:
      secretName: tls-localhost-dev
      dnsNames:
        - localhost
      issuerRef:
        name: letsencrypt-dev-issuer
        kind: Issuer
   ```

This time after running `skaffold dev`, and `minikube tunnel`, my app is running with the TLS certificates like it should be.
